#!/usr/bin/env python3
"""Create or verify the private byte-exact archive of ``results/evaluation``.

Create mode copies every file under ``--source`` into ``<target>/evaluation/``
byte-for-byte and materializes a browsable export of every record's
``translated_files`` under ``<target>/translated_files_export/``. It records
the archive's per-file SHA-256 inventory and aggregate SHA-256 both inside the
archive (``ARCHIVE_MANIFEST.json``) and in the tracked provenance manifest
given by ``--manifest`` (its ``archives`` section, keyed by target basename).

The archive is never overwritten: a rerun against an existing target whose
content differs from what this source would produce exits nonzero without
writing anything. ``--check`` re-hashes an existing target and compares it to
the provenance-manifest record, exiting nonzero on any divergence.

The target must never lie inside the repository's ``results/evaluation``.
"""

from __future__ import annotations

import argparse
import datetime
import hashlib
import json
import pathlib
import shutil
import sys

ARCHIVE_MANIFEST_NAME = "ARCHIVE_MANIFEST.json"


def sha256_bytes(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def sha256_file(path: pathlib.Path) -> str:
    h = hashlib.sha256()
    with open(path, "rb") as fh:
        for chunk in iter(lambda: fh.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def aggregate_sha256(files: dict[str, str]) -> str:
    h = hashlib.sha256()
    for rel in sorted(files):
        h.update(f"{rel}\t{files[rel]}\n".encode())
    return h.hexdigest()


def _safe_member(name: str) -> bool:
    p = pathlib.PurePosixPath(name)
    return not p.is_absolute() and ".." not in p.parts and len(p.parts) >= 1


def plan_archive(source: pathlib.Path) -> dict[str, pathlib.Path | bytes]:
    """Map archive-relative path -> source file path or generated bytes."""
    plan: dict[str, pathlib.Path | bytes] = {}
    for p in sorted(source.rglob("*")):
        if p.is_file():
            rel = p.relative_to(source).as_posix()
            plan[f"evaluation/{rel}"] = p
    for record_path in sorted(source.rglob("*.json")):
        try:
            record = json.loads(record_path.read_text())
        except (OSError, json.JSONDecodeError, UnicodeDecodeError):
            continue
        translated = record.get("translated_files") if isinstance(record, dict) else None
        if not isinstance(translated, dict):
            continue
        rel_dir = record_path.relative_to(source).with_suffix("").as_posix()
        for fname, content in sorted(translated.items()):
            if not isinstance(content, str) or not _safe_member(fname):
                continue
            plan[f"translated_files_export/{rel_dir}/{fname}"] = content.encode()
    return plan


def plan_hashes(plan: dict[str, pathlib.Path | bytes]) -> dict[str, str]:
    return {
        rel: sha256_file(src) if isinstance(src, pathlib.Path) else sha256_bytes(src)
        for rel, src in plan.items()
    }


def existing_hashes(target: pathlib.Path) -> dict[str, str]:
    files: dict[str, str] = {}
    for p in sorted(target.rglob("*")):
        if p.is_file() and p.name != ARCHIVE_MANIFEST_NAME:
            files[p.relative_to(target).as_posix()] = sha256_file(p)
    return files


def _diff_summary(expected: dict[str, str], actual: dict[str, str]) -> list[str]:
    msgs = []
    for rel in sorted(set(expected) - set(actual)):
        msgs.append(f"missing from archive: {rel}")
    for rel in sorted(set(actual) - set(expected)):
        msgs.append(f"unexpected in archive: {rel}")
    for rel in sorted(set(expected) & set(actual)):
        if expected[rel] != actual[rel]:
            msgs.append(f"hash mismatch: {rel}")
    return msgs


def _load_manifest(path: pathlib.Path) -> dict:
    return json.loads(path.read_text())


def create(source: pathlib.Path, target: pathlib.Path,
           manifest_path: pathlib.Path) -> int:
    source = source.resolve()
    target_resolved = target.expanduser().resolve()
    if not source.is_dir():
        print(f"ERROR: source {source} is not a directory")
        return 2
    forbidden = source.resolve()
    if target_resolved == forbidden or forbidden in target_resolved.parents:
        print(f"ERROR: refusing target inside the immutable source tree: {target_resolved}")
        return 2

    plan = plan_archive(source)
    expected = plan_hashes(plan)

    if target_resolved.exists() and any(target_resolved.iterdir()):
        actual = existing_hashes(target_resolved)
        diffs = _diff_summary(expected, actual)
        if diffs:
            for msg in diffs[:20]:
                print(f"FAIL  {msg}")
            print(f"REFUSED: existing archive at {target_resolved} differs from "
                  f"this source ({len(diffs)} difference(s)); it will not be overwritten.")
            return 2
        print(f"Existing archive at {target_resolved} already matches this source; "
              f"nothing written.")
        _record(manifest_path, target_resolved, expected, note="verified-existing")
        return 0

    target_resolved.mkdir(parents=True, exist_ok=True)
    for rel, src in plan.items():
        dest = target_resolved / rel
        dest.parent.mkdir(parents=True, exist_ok=True)
        if isinstance(src, pathlib.Path):
            shutil.copyfile(src, dest)
        else:
            dest.write_bytes(src)
    actual = existing_hashes(target_resolved)
    diffs = _diff_summary(expected, actual)
    if diffs:
        for msg in diffs[:20]:
            print(f"FAIL  {msg}")
        print("ERROR: archive verification failed immediately after writing")
        return 2
    _record(manifest_path, target_resolved, expected, note="created")
    print(f"Archive created at {target_resolved}: {len(expected)} files, "
          f"aggregate {aggregate_sha256(expected)[:16]}")
    return 0


def _record(manifest_path: pathlib.Path, target: pathlib.Path,
            files: dict[str, str], note: str) -> None:
    agg = aggregate_sha256(files)
    archive_manifest = {
        "archive_name": target.name,
        "file_count": len(files),
        "aggregate_sha256": agg,
        "files": files,
    }
    (target / ARCHIVE_MANIFEST_NAME).write_text(
        json.dumps(archive_manifest, indent=1, sort_keys=True) + "\n"
    )
    manifest = _load_manifest(manifest_path)
    entry = {
        "target": str(target),
        "file_count": len(files),
        "aggregate_sha256": agg,
        "recorded_at": datetime.datetime.now(datetime.UTC).isoformat(),
        "note": note,
    }
    existing = manifest.setdefault("archives", {}).get(target.name)
    if existing and existing.get("aggregate_sha256") != agg:
        # never silently repoint the provenance record at different bytes
        print(f"ERROR: provenance manifest already records archive "
              f"'{target.name}' with a different aggregate hash; not updating.")
        raise SystemExit(2)
    manifest["archives"][target.name] = entry
    manifest_path.write_text(json.dumps(manifest, indent=1, sort_keys=True) + "\n")


def check(target: pathlib.Path, manifest_path: pathlib.Path) -> int:
    target = target.expanduser().resolve()
    manifest = _load_manifest(manifest_path)
    entry = (manifest.get("archives") or {}).get(target.name)
    if not entry:
        print(f"FAIL  no archive named '{target.name}' recorded in {manifest_path}")
        return 1
    if not target.is_dir():
        print(f"FAIL  archive directory missing: {target}")
        return 1
    internal_path = target / ARCHIVE_MANIFEST_NAME
    if not internal_path.is_file():
        print(f"FAIL  {ARCHIVE_MANIFEST_NAME} missing from archive")
        return 1
    internal = json.loads(internal_path.read_text())
    actual = existing_hashes(target)
    diffs = _diff_summary(internal.get("files", {}), actual)
    agg = aggregate_sha256(actual)
    if entry["aggregate_sha256"] != agg:
        diffs.append(
            f"aggregate mismatch vs provenance manifest: "
            f"recorded {entry['aggregate_sha256'][:16]}, actual {agg[:16]}"
        )
    if entry.get("file_count") != len(actual):
        diffs.append(f"file count mismatch: recorded {entry.get('file_count')}, "
                     f"actual {len(actual)}")
    if diffs:
        for msg in diffs[:20]:
            print(f"FAIL  {msg}")
        print(f"CHECK FAILED: {len(diffs)} divergence(s)")
        return 1
    print(f"CHECK OK: {len(actual)} files, aggregate {agg[:16]}")
    return 0


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--source", type=pathlib.Path,
                    help="directory to archive (create mode)")
    ap.add_argument("--target", required=True, type=pathlib.Path)
    ap.add_argument("--manifest", required=True, type=pathlib.Path,
                    help="tracked provenance manifest (inventory JSON)")
    ap.add_argument("--check", action="store_true",
                    help="verify an existing archive against the manifest record")
    args = ap.parse_args(argv)

    if args.check:
        return check(args.target, args.manifest)
    if not args.source:
        ap.error("--source is required unless --check is given")
    return create(args.source, args.target, args.manifest)


if __name__ == "__main__":
    sys.exit(main())
